### ISSUE TITLE
Please Re-write the Tutorial

### ISSUE THREAD

**Issue by frakman1** [gitpitch/in-60-seconds#1]
This 'Tutorial' doesn't make sense (to me). 

- Do you want me to clone this repo and git add/commit/push its PITCHME.md file? - `Didn't Work`
- Do you want me to create a repo locally and add this file to it and then git add/commit/push?  - `Didn't Work Either`

Your website's 'Intro' is not an intro. It's a Promo. Show a video of someone _**actually**_ creating a presentation instead of that promo.

This 'Tutorial' is not a tutorial. It is a wish. I know you want to make it seem simple but it is not straightforward and none of this makes sense. **_What_** is actually doing the markdown translation to slides and **_where_** do these files reside? What pieces are involved??

The website says:
```
Presentations are instantly available online following a git-push:
https://gitpitch.com/$user/$repo/$branch
```
following a git-push to **_WHERE_**? No mention of a repo is made anywhere.
_<sub>(Thank you for making me type that URL out because it's an image masquerading as text that I can't copy and paste.) </sub>_
 If a` $user` is expected? Do I  have to open an account with gitpitch?

Please write fuller instructions that takes into account a user who isn't familiar with your product.

---
**  **UPDATE** **
--
I finally figured it out. I had to: 
* Create a **separate** personal repo in Github with the PITCHME.md file in it. 
* Then I had to type out the image masquerading as text on your website:

https://gitpitch.com/$user/$repo/$branch

and make the following substitutions:

  * $user -> my GitHub username
  * $repo -> the new repo I just created
  * $branch -> `master` by default

The resultant URL loos like this:  `https://gitpitch.com/frakman1/mygitpitch/master`

Only then was I able to go to **YOUR** website that then goes out to **MY** repo and does the translation of **MY** PITCHME.md file and presents it in the browser. 

This last sentence is crucial to understanding what is going on here. It it not obvious. It is not intuitive and all the marketing jargon in the world won't  make it so.

**Comment by gitpitch** [comment]
Thanks for this feedback. I have revised the tutorial content to make each step more explicit. The changes in the text attempt to minimize or entirely eradicate any need for `discovery` on the part of the reader. Let me know what you think.

**Comment by frakman1** [comment]
Excellent. I love it now. Thank you for indulging me.
