### ISSUE TITLE
Accept more links

### ISSUE THREAD

**Issue by muescha** [gitpitch/in-60-seconds#10]
Accept also links like this:

https://gitpitch.com/gitpitch/in-60-seconds/blob/master/PITCHME.md

**Comment by gitpitch** [comment]
I assume the purpose of this request is to access the *raw* markdown for a presentation. You can already do that using the links provided in the slideshow menu. See the [docs](https://gitpitch.com/docs/foundation-features/slideshow-menu/) for details. Just click on the **PITCHME.md** link in the slideshow menu panel.

**Comment by muescha** [comment]
No. I like to see the presentation and not an error

Because in this readme is no mention how I see the presentation - then I just renamed the domain as in many other services like this. 

So I expect just rename anytime the link from GitHub.com to Gitpitch.com to see the presentation and not receive an error. 

For this you have to check if the branch name is `blob` and then use the next section from path

**Comment by muescha** [comment]
Or if the filename is `*.md` then show this presentation. It is to save many slides in one repo or in a doc folder ...
