### ISSUE TITLE
Don't put to much into the main folder

### ISSUE THREAD

**Issue by muescha** [gitpitch/in-60-seconds#9]
I think not everyone like the current too generic `asset` folder. 

Suggestion:
- any more specific directory (for example `/PITCHME-assets/`)
- `PITCHME.yaml` should also go into this folder
- a frontmatter (#8) in the `PITCHME.md` should have a assets setting

**Comment by gitpitch** [comment]
Thank you for your suggestions.

The use of an `assets` directory is just a convention. You are free to override this convention and use any asset directory structure your wish. Just make sure you reference the correct path to your assets in your `PITCHME.md` and `PITCHME.yaml` files.

The `PITCHME.yaml` file living alongside the `PITCHME.md` is also a convention. This convention can not be overridden.

GitPitch will not be adopting frontmatter at this time.

**Comment by muescha** [comment]
Then you should update the example or the readme that this name is free and not a convention

**Comment by muescha** [comment]
Just a side note. If I have a README.md then it is easy to see what's going on. 

But the PITCHME comes always with `.md` and `.yaml` and someone which is not familiar with this convention always at first decide to which is one and is distracted
 
Just my 2 cents
